# -*- coding: utf-8 -*-
"""agglomerative clustring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DZZfWKqlOlBv0AfNhkUIZVWVnuWTJwa
"""

### agglomerative clustring
! pip install mglearn
import mglearn
import matplotlib.pyplot as plt
import numpy as np

mglearn.plots.plot_agglomerative_algorithm()

from sklearn.cluster import AgglomerativeClustering
from sklearn.datasets import make_blobs

agg = AgglomerativeClustering(n_clusters=3)
X, y = make_blobs(random_state=1)

assignment = agg.fit_predict(X)

mglearn.discrete_scatter(X[:, 0], X[:, 1], assignment)
plt.xlabel("Feature 0")
plt.ylabel("Feature 1")
plt.show()

mglearn.plots.plot_agglomerative()

from scipy.cluster.hierarchy import dendrogram, ward
from sklearn.datasets import make_blobs

X, y = make_blobs(random_state=0, n_samples=12)
linkage_array = ward(X)
dendrogram(linkage_array)

ax = plt.gca()
bounds = ax.get_xbound()
ax.plot(bounds, [7.25, 7.25], '--', c='k')
ax.plot(bounds, [4, 4], '--', c='k')

ax.text(bounds[1], 7.25, 'two clusters', va='center')
ax.text(bounds[1], 4, 'three clusters', va='center')

plt.xlabel("Sample index")
plt.ylabel("Cluster distance")

